name: thesis-pdf
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install TeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra latexmk biber python3-pygments
      - name: Build PDF
        run: latexmk -pdf -interaction=nonstopmode -synctex=1 -shell-escape -outdir=out main.tex
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: out/main.pdf
